channels:
- conda-forge
dependencies:
- python=3.12.12
- pip<=24.1.2
- pip:
  - mlflow==3.7.0
  - cloudpickle==3.1.2
  - ipywidgets==7.7.1
  - numpy==2.0.2
  - pandas==2.2.2
  - scikit-learn==1.6.1
  - scipy==1.16.3
  - xgboost==3.1.2
name: mlflow-env
