# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# ===============================================
# app.py — Bankruptcy Early Warning Indicator
# Master Controller for Multi-Page Streamlit App
# ===============================================

import streamlit as st
from utils.model_utils import load_model
from utils.shap_utils import load_shap_explainer
from utils.visualization import inject_global_css
import os

# --------------------------------------------------------
# STREAMLIT CONFIG
# --------------------------------------------------------
st.set_page_config(
    page_title="Bankruptcy Early Warning Indicator",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --------------------------------------------------------
# GLOBAL DARK MODE + GLASSMORPHISM CSS
# --------------------------------------------------------
inject_global_css()

# --------------------------------------------------------
# SIDEBAR NAVIGATION
# --------------------------------------------------------
with st.sidebar:
    st.image("assets/logo.png", width=160)

    st.markdown("### Navigation")

    st.page_link("app.py", label="Overview")
    st.page_link("pages/2_🔍_Analysis.py", label="Single Company Analysis")
    st.page_link("pages/3_🎮_Simulator.py", label="Scenario Simulator")
    st.page_link("pages/4_📊_Portfolio.py", label="Portfolio Analysis")
    st.page_link("pages/5_📄_Reports.py", label="Reports & Exports")

    st.markdown("---")
    st.markdown("### Quick Stats")
    q = st.session_state.get("quick_stats", {})
    single_label = q.get("single_label", "—")
    single_prob = q.get("single_proba", None)
    single_prob_str = f"{single_prob:.2%}" if single_prob is not None else "—"
    portfolio_avg = q.get("portfolio_avg", None)
    portfolio_avg_str = f"{portfolio_avg:.2%}" if portfolio_avg is not None else "—"
    companies = q.get("companies", "—")
    st.info(f"Last Single Risk: {single_prob_str} ({single_label})\n"
            f"Portfolio Avg Risk: {portfolio_avg_str}\n"
            f"Companies Scored: {companies}")

# --------------------------------------------------------
# LOAD GLOBAL MODEL + SHAP EXPLAINER
# --------------------------------------------------------
@st.cache_resource
def _load_resources():
    model = load_model()
    shap_explainer = load_shap_explainer(model)
    return model, shap_explainer

model, shap_explainer = _load_resources()

# --------------------------------------------------------
# HOME PAGE CONTENT
# --------------------------------------------------------
st.markdown(
    """
    <div style="
        text-align:center;
        padding: 28px 0 8px 0;
    ">
        <h1 style="margin-bottom:8px;">Bankruptcy Early Warning Indicator</h1>
        <p style="font-size:18px; margin:0;">Enterprise-grade financial distress prediction platform</p>
        <p style="font-size:16px; margin:4px 0 0 0; opacity:0.85;">
            Use the sidebar to navigate the analysis, simulation, portfolio, and reporting workflows.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# -----------------------------
# Quick launch tiles
# -----------------------------
st.markdown("")
c1, c2, c3, c4 = st.columns(4)

with c1:
    st.markdown(
        """
        <div class="metric-card">
            <h4 style="margin-bottom:6px;">Single Analysis</h4>
            <p style="margin:0; opacity:0.9;">Assess one company with full SHAP explainability.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.page_link("pages/2_🔍_Analysis.py", label="Open Analysis")

with c2:
    st.markdown(
        """
        <div class="metric-card">
            <h4 style="margin-bottom:6px;">Scenario Simulator</h4>
            <p style="margin:0; opacity:0.9;">Model impact of revenue, cost, and leverage changes.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.page_link("pages/3_🎮_Simulator.py", label="Open Simulator")

with c3:
    st.markdown(
        """
        <div class="metric-card">
            <h4 style="margin-bottom:6px;">Portfolio Scoring</h4>
            <p style="margin:0; opacity:0.9;">Batch score thousands of companies and filter risk.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.page_link("pages/4_📊_Portfolio.py", label="Open Portfolio")

with c4:
    st.markdown(
        """
        <div class="metric-card">
            <h4 style="margin-bottom:6px;">Reports & Exports</h4>
            <p style="margin:0; opacity:0.9;">Generate PDF deliverables and summary exports.</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.page_link("pages/5_📄_Reports.py", label="Open Reports")

# -----------------------------
# Highlights section
# -----------------------------
st.markdown("<br>", unsafe_allow_html=True)
st.markdown("### Platform Highlights")

g1, g2 = st.columns(2)
with g1:
    st.markdown(
        """
        <div class="glass-card fade-in">
            <h4>Modeling</h4>
            <ul>
                <li>CatBoost classifier with calibrated probabilities</li>
                <li>Feature-engineered financial ratios for robustness</li>
                <li>SHAP explainability for every prediction</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True,
    )
with g2:
    st.markdown(
        """
        <div class="glass-card fade-in">
            <h4>Reporting & Ops</h4>
            <ul>
                <li>Portfolio batch scoring with CSV/XLSX uploads</li>
                <li>Professional PDF reports with SHAP visuals</li>
                <li>AI-assisted summaries (when API key provided)</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True,
    )