# -*- coding: utf-8 -*-
"""ai_summary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# ==============================================================
# utils/ai_summary.py
# LLM-powered executive summary & recommendations (Anthropic)
# ==============================================================

import os
import streamlit as st
from anthropic import Anthropic, HUMAN_PROMPT, AI_PROMPT


# --------------------------------------------------------------
# INITIALIZE ANTHROPIC CLIENT (cached)
# --------------------------------------------------------------
@st.cache_resource
def load_anthropic_client():
    """
    Loads the Anthropic client using API key from environment variables.
    Returns None if key is missing (fails gracefully).
    """
    api_key = os.getenv("ANTHROPIC_API_KEY")

    if not api_key:
        st.warning("Anthropic API key not found. Executive summaries won't work.")
        return None

    try:
        client = Anthropic(api_key=api_key)
        return client
    except Exception as e:
        st.error(f"❌ Failed to initialize Anthropic: {e}")
        return None


# --------------------------------------------------------------
# EXECUTIVE SUMMARY GENERATION
# --------------------------------------------------------------
def generate_executive_summary(company_data: dict, shap_drivers: list) -> str:
    """
    Generates a professional, multi-paragraph executive summary covering:
    - Financial condition
    - Bankruptcy risk
    - Key drivers (SHAP)
    - Recommendations
    """

    client = load_anthropic_client()
    if client is None:
        return "AI summary unavailable: Missing Anthropic API key."

    # Prepare structured input for the model
    company_block = "\n".join([f"- {k}: {v}" for k, v in company_data.items()])
    shap_block = "\n".join([f"- {d['feature']}: SHAP {d['shap_value']:.4f}" for d in shap_drivers])

    prompt = f"""
You are a senior financial analyst writing an executive summary for a Bankruptcy Early Warning Report.

Write a polished 3–4 paragraph executive summary with clear business language. Include:

1. **Overall financial health overview**
2. **Bankruptcy probability and interpretation**
3. **Top risk drivers from SHAP (explain in plain English)**
4. **Recommended next steps for management**

Here is the structured data:

Company Financials:
{company_block}

Key SHAP Risk Drivers:
{shap_block}

Now write the executive summary:
"""

    try:
        response = client.completions.create(
            model="claude-3-sonnet-20240229",
            max_tokens=900,
            temperature=0.3,
            prompt=f"{HUMAN_PROMPT} {prompt} {AI_PROMPT}"
        )

        summary = response.completion.strip()
        return summary

    except Exception as e:
        return f"AI summary unavailable due to error: {e}"


# --------------------------------------------------------------
# RECOMMENDATION ENGINE VIA LLM
# --------------------------------------------------------------
def generate_ai_recommendations(company_data: dict, shap_drivers: list) -> list:
    """
    Returns 5–7 highly actionable recommendations as a list of strings.
    """

    client = load_anthropic_client()
    if client is None:
        return ["AI recommendations unavailable: Missing Anthropic API key."]

    company_block = "\n".join([f"- {k}: {v}" for k, v in company_data.items()])
    shap_block = "\n".join([f"- {d['feature']}: SHAP {d['shap_value']:.4f}" for d in shap_drivers])

    prompt = f"""
Your task is to generate 5–7 extremely actionable and financially sound recommendations
for reducing bankruptcy risk.

Use the company’s financials and SHAP drivers below:

Financials:
{company_block}

SHAP Drivers:
{shap_block}

Guidelines:
- Recommendations must be specific and data-backed
- Use professional finance terminology
- Each item should be 1–2 sentences

Return ONLY the list of recommendations in bullet form.
"""

    try:
        response = client.completions.create(
            model="claude-3-sonnet-20240229",
            max_tokens=1000,
            temperature=0.4,
            prompt=f"{HUMAN_PROMPT} {prompt} {AI_PROMPT}"
        )

        text = response.completion.strip()
        lines = [l.strip("-• ").strip() for l in text.split("\n") if l.strip()]

        return lines

    except Exception as e:
        return [f"AI recommendations unavailable due to error: {e}"]