# -*- coding: utf-8 -*-
"""feature_engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# =====================================================
# utils/feature_engineering.py
# Computes all engineered financial ratios used in model
# =====================================================

import pandas as pd
import numpy as np

# -----------------------------------------------------
# MASTER FEATURE ENGINEERING FUNCTION
# -----------------------------------------------------
def compute_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Applies all engineered financial ratios exactly matching
    the training pipeline used in the CatBoost model.

    Inputs:
        df: DataFrame containing raw financial fields

    Returns:
        df: DataFrame with engineered ratios added
    """

    df = df.copy()

    # -------------------------------
    # SAFETY: prevent division errors
    # -------------------------------
    def safe_div(numerator, denominator):
        return numerator / denominator.replace({0: np.nan})

    # -------------------------------
    # ENGINEERED FEATURES
    # -------------------------------
    df["leverage"] = safe_div(df["total_liabilities"], df["total_assets"])
    df["profit_margin"] = safe_div(df["net_income"], df["net_sales"])
    df["ebitda_margin"] = safe_div(df["ebitda"], df["net_sales"])
    df["revenue_efficiency"] = safe_div(df["total_revenue"], df["total_assets"])
    df["operating_expense_ratio"] = safe_div(df["total_operating_expenses"], df["total_revenue"])
    df["working_capital_ratio"] = safe_div(
        (df["current_assets"] - df["total_current_liabilities"]),
        df["total_assets"]
    )

    # -------------------------------
    # FINAL CLEANUP
    # -------------------------------
    numeric_cols = df.select_dtypes(include=["float", "int"]).columns
    df[numeric_cols] = df[numeric_cols].fillna(0.0)

    return df