# -*- coding: utf-8 -*-
"""pdf_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# =====================================================================
# utils/pdf_generator.py — PHASE 3
# Enterprise PDF Generator for:
#  - Single Company Reports
#  - Multi-Company Portfolio Reports
#  - Scenario Appendices
# =====================================================================

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    Paragraph, Frame, Spacer, Image, Table, TableStyle, PageBreak
)
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import io
import pandas as pd
import numpy as np

styles = getSampleStyleSheet()

# -------------------------------------------------------------
# STYLES
# -------------------------------------------------------------
title_style = ParagraphStyle(
    "TitleLarge",
    parent=styles["Title"],
    fontSize=26,
    textColor=colors.HexColor("#1E3A8A"),
    spaceAfter=20,
)

header_style = ParagraphStyle(
    "Header",
    parent=styles["Heading2"],
    fontSize=20,
    textColor=colors.HexColor("#1E3A8A"),
    spaceAfter=12,
)

section_style = ParagraphStyle(
    "Section",
    parent=styles["Heading3"],
    fontSize=15,
    textColor=colors.HexColor("#1E3A8A"),
    spaceAfter=8,
)

body_style = ParagraphStyle(
    "Body",
    parent=styles["BodyText"],
    fontSize=11,
    leading=14,
)

table_header_style = ParagraphStyle(
    "TableHeader",
    parent=styles["BodyText"],
    fontSize=12,
    textColor=colors.HexColor("#1E3A8A"),
    leading=14,
    spaceAfter=4,
)


# =====================================================================
# MAIN PDF GENERATOR
# =====================================================================
def generate_pdf(report_data: dict) -> bytes:
    """
    Multi-purpose PDF generator for:
      1. Single-company report
      2. Multi-company portfolio report

    Expected keys in report_data:
      - company_name
      - risk_score
      - risk_label
      - shap_text_summary
      - recommendations
      - waterfall_image (path or None)
      - radar_image (path or None)
      - top_drivers_table (DataFrame or None)

      PORTFOLIO MODE KEYS:
      - portfolio_mode (bool)
      - portfolio_table (DataFrame)
    """

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # =================================================================
    # COVER PAGE (COMMON FOR SINGLE + PORTFOLIO)
    # =================================================================
    pdf.setFillColor(colors.HexColor("#1E3A8A"))
    pdf.rect(0, 0, width, height, fill=1)

    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 32)
    pdf.drawString(50, height - 100, "Bankruptcy Early Warning Report")

    pdf.setFont("Helvetica", 18)
    pdf.drawString(50, height - 140, f"{report_data.get('company_name', 'Portfolio Report')}")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 170, "Generated by Bankruptcy Early Warning Indicator Platform")

    pdf.showPage()

    # =================================================================
    # PORTFOLIO REPORT MODE
    # =================================================================
    if report_data.get("portfolio_mode", False):

        portfolio_df: pd.DataFrame = report_data["portfolio_table"]

        # SUMMARY PAGE
        pdf.setFont("Helvetica-Bold", 24)
        pdf.drawString(50, height - 60, "Portfolio Summary")

        avg_risk = portfolio_df["bankruptcy_probability"].mean()
        pdf.setFont("Helvetica", 14)

        pdf.drawString(50, height - 110, f"Average Portfolio Risk: {avg_risk:.2%}")
        pdf.drawString(50, height - 135, f"Total Companies: {portfolio_df.shape[0]}")

        pdf.line(50, height - 150, width - 50, height - 150)
        pdf.showPage()

        # PORTFOLIO APPENDIX TABLE
        pdf.setFont("Helvetica-Bold", 22)
        pdf.drawString(50, height - 60, "Portfolio Appendix")

        df = portfolio_df.copy()
        df = df.sort_values("bankruptcy_probability", ascending=False)

        # Table split across multiple PDF pages
        rows = [["Company", "Risk Score", "MajorGroup"]] + \
               df[["company_name", "bankruptcy_probability", "MajorGroup"]] \
               .apply(lambda r: [str(r["company_name"]), f"{r['bankruptcy_probability']:.2%}", str(r["MajorGroup"])], axis=1).tolist()


        # chunk size for each PDF page
        chunk_size = 30

        for i in range(0, len(rows), chunk_size):
            chunk = rows[i:i + chunk_size]

            table = Table(chunk, colWidths=[200, 150, 100])
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
            ]))

            frame = Frame(50, 50, width - 100, height - 120)
            frame.addFromList([table], pdf)

            pdf.showPage()

        pdf.save()
        buffer.seek(0)
        return buffer.getvalue()

    # =================================================================
    # SINGLE COMPANY REPORT MODE
    # =================================================================

    # ---------------------------------------------------------
    # PAGE 2 — RISK SUMMARY
    # ---------------------------------------------------------
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(50, height - 60, "Financial Health Summary")

    pdf.setFont("Helvetica", 14)
    pdf.drawString(50, height - 110, f"Bankruptcy Probability: {report_data['risk_score']:.2%}")
    pdf.drawString(50, height - 140, f"Risk Classification: {report_data['risk_label']}")

    pdf.line(50, height - 155, width - 50, height - 155)
    pdf.showPage()

    # ---------------------------------------------------------
    # PAGE 3 — EXECUTIVE SUMMARY
    # ---------------------------------------------------------
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(50, height - 60, "Executive Summary")

    frame = Frame(50, 80, width - 100, height - 150)
    summary_para = Paragraph(report_data["shap_text_summary"], body_style)
    frame.addFromList([summary_para], pdf)

    pdf.showPage()

    # ---------------------------------------------------------
    # PAGE 4 — SHAP WATERFALL IMAGE
    # ---------------------------------------------------------
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(50, height - 60, "SHAP Waterfall Analysis")

    if report_data.get("waterfall_image"):
        try:
            img = Image(report_data["waterfall_image"], width=6 * inch, height=4 * inch)
            frame = Frame(50, 120, width - 100, height - 240)
            frame.addFromList([img], pdf)
        except:
            pdf.drawString(50, height - 100, "⛔ Error loading waterfall chart")
    else:
        pdf.drawString(50, height - 100, "⛔ No SHAP waterfall available")

    pdf.showPage()

    # ---------------------------------------------------------
    # PAGE 5 — RADAR CHART IMAGE
    # ---------------------------------------------------------
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(50, height - 60, "Financial Health Radar Chart")

    if report_data.get("radar_image"):
        try:
            img2 = Image(report_data["radar_image"], width=6 * inch, height=4 * inch)
            frame2 = Frame(50, 120, width - 100, height - 240)
            frame2.addFromList([img2], pdf)
        except:
            pdf.drawString(50, height - 100, "⛔ Error loading radar chart")
    else:
        pdf.drawString(50, height - 100, "⛔ No radar chart available")

    pdf.showPage()

    # ---------------------------------------------------------
    # PAGE 6 — TOP SHAP DRIVERS TABLE
    # ---------------------------------------------------------
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(50, height - 60, "Top SHAP Drivers")

    drivers_df: pd.DataFrame = report_data.get("top_drivers_table")

    if drivers_df is not None:
        rows = (
            [["Feature", "SHAP Value"]]
            + drivers_df[["feature", "shap_value"]]
            .apply(lambda r: [r["feature"], f"{r['shap_value']:.4f}"], axis=1)
            .tolist()
        )

        table = Table(rows, colWidths=[250, 150])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
        ]))

        frame = Frame(50, 80, width - 100, height - 150)
        frame.addFromList([table], pdf)

    else:
        pdf.drawString(50, height - 100, "⛔ No SHAP driver data available")

    pdf.showPage()

    # ---------------------------------------------------------
    # PAGE 7 — RECOMMENDATIONS
    # ---------------------------------------------------------
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(50, height - 60, "Recommended Actions")

    if report_data.get("recommendations"):
        items = "<br/>".join([f"• {rec}" for rec in report_data["recommendations"]])
        frame = Frame(50, 80, width - 100, height - 150)
        frame.addFromList([Paragraph(items, body_style)], pdf)
    else:
        pdf.drawString(50, height - 100, "No recommendations available")

    pdf.showPage()

    # ---------------------------------------------------------
    # FINISH
    # ---------------------------------------------------------
    pdf.save()
    buffer.seek(0)
    return buffer.getvalue()
