# -*- coding: utf-8 -*-
"""plot_helpers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# ============================================================
# utils/plot_helpers.py
# Advanced Plotly visualizations for the Bankruptcy Platform
# ============================================================

import plotly.graph_objects as go
import plotly.express as px
import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 1. SHAP WATERFALL CHART (INTERACTIVE)
# ------------------------------------------------------------
def plot_shap_waterfall(shap_values, base_value, feature_names, top_n=8):
    """
    Creates an interactive SHAP waterfall chart using Plotly.

    Inputs:
        shap_values: 1D array of SHAP values
        base_value: expected value (SHAP base)
        feature_names: list of feature names corresponding to shap_values
    """

    # Select top N drivers
    abs_vals = np.abs(shap_values)
    idx = np.argsort(abs_vals)[::-1][:top_n]

    labels = [feature_names[i] for i in idx]
    values = shap_values[idx]

    colors = ["#EF4444" if v > 0 else "#10B981" for v in values]

    fig = go.Figure(go.Waterfall(
        name="SHAP",
        orientation="v",
        measure=["relative"] * len(values),
        x=labels,
        y=values,
        text=[f"{v:.4f}" for v in values],
        textposition="auto",
        decreasing={"marker":{"color": "#EF4444"}},
        increasing={"marker":{"color": "#10B981"}},
        connector={"line":{"color":"white"}}
    ))

    fig.update_layout(
        title="SHAP Waterfall — Contribution of Features to Bankruptcy Risk",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(17,24,39,0.6)",
        font=dict(color="white"),
        height=500
    )

    return fig


# ------------------------------------------------------------
# 2. FINANCIAL HEALTH RADAR CHART
# ------------------------------------------------------------
def plot_radar_chart(company_vals, industry_vals, labels):
    """
    Radar chart comparing company ratios vs industry median benchmarks.

    Inputs:
        company_vals: list of values for the company
        industry_vals: list of benchmark values
        labels: list of axis labels
    """

    fig = go.Figure()

    fig.add_trace(go.Scatterpolar(
        r=company_vals,
        theta=labels,
        fill="toself",
        name="Company",
        line_color="#3B82F6"
    ))

    fig.add_trace(go.Scatterpolar(
        r=industry_vals,
        theta=labels,
        fill="toself",
        name="Industry Median",
        line_color="#FBBF24"
    ))

    fig.update_layout(
        polar=dict(
            bgcolor="rgba(0,0,0,0)",
            radialaxis=dict(visible=True, color="white")
        ),
        paper_bgcolor="rgba(0,0,0,0)",
        font=dict(color="white"),
        title="Financial Health Radar Chart"
    )

    return fig


# ------------------------------------------------------------
# 3. SENSITIVITY TORNADO CHART
# ------------------------------------------------------------
def plot_tornado_chart(labels, impacts):
    """
    Tornado chart showing sensitivity of variables to risk score.
    """

    # Sort by absolute magnitude
    df = pd.DataFrame({"labels": labels, "impact": impacts})
    df["abs"] = df["impact"].abs()
    df = df.sort_values("abs", ascending=True)

    fig = go.Figure(go.Bar(
        x=df["impact"],
        y=df["labels"],
        orientation="h",
        marker_color=df["impact"].apply(lambda x: "#EF4444" if x > 0 else "#10B981")
    ))

    fig.update_layout(
        title="Scenario Sensitivity (Tornado Chart)",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(17,24,39,0.6)",
        font=dict(color="white"),
        height=500
    )

    return fig


# ------------------------------------------------------------
# 4. INDUSTRY RISK HEATMAP
# ------------------------------------------------------------
def plot_industry_heatmap(df, industry_col="MajorGroup"):
    """
    Treemap heatmap of risk by industry.
    """

    fig = px.treemap(
        df,
        path=[industry_col],
        values="bankruptcy_probability",
        color="bankruptcy_probability",
        color_continuous_scale=["#10B981", "#F59E0B", "#EF4444"],
        title="Industry Bankruptcy Risk Heatmap"
    )

    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        font=dict(color="white")
    )

    return fig