# -*- coding: utf-8 -*-
"""visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# ======================================================
# utils/visualization.py
# Global UI Theme: Dark Mode + Glassmorphism Styling
# ======================================================

import streamlit as st

# ------------------------------------------------------
# Inject Global CSS (Dark Theme + Glassmorphism + Layout)
# ------------------------------------------------------
def inject_global_css():
    """
    Injects custom CSS into Streamlit to create:
    - Dark theme
    - Glassmorphism surfaces
    - Gradient cards
    - Smooth animations
    - Finance-grade UI look
    """
    st.markdown("""
    <style>

    /* -------------------------------------------
       GLOBAL BACKGROUND + TEXT
    ------------------------------------------- */
    body {
        background-color: #0f172a !important; /* Slate-900 style dark */
        color: #e2e8f0 !important; /* Slate-200 */
        font-family: 'Inter', sans-serif;
    }

    .main .block-container {
        padding-top: 1.5rem;
        padding-bottom: 2rem;
        max-width: 1180px;
    }

    /* -------------------------------------------
       REMOVE WHITE BACKGROUND FLASH
    ------------------------------------------- */
    .stApp {
        background: #0f172a !important;
    }

    /* -------------------------------------------
       GLASS CARD STYLE
    ------------------------------------------- */
    .glass-card {
        background: linear-gradient(135deg, rgba(255,255,255,0.05), rgba(255,255,255,0.03));
        border-radius: 16px;
        padding: 22px;
        backdrop-filter: blur(14px);
        border: 1px solid rgba(255, 255, 255, 0.10);
        transition: 0.3s ease;
    }

    .glass-card:hover {
        background: rgba(255, 255, 255, 0.12);
        transform: translateY(-3px);
    }

    /* -------------------------------------------
       METRIC CARDS WITH GRADIENT
    ------------------------------------------- */
    .metric-card {
        background: linear-gradient(135deg, #1E3A8A, #0f172a);
        padding: 18px;
        border-radius: 14px;
        color: white;
        text-align: center;
        transition: 0.3s ease;
        border: 1px solid rgba(255,255,255,0.08);
        box-shadow: 0 10px 30px rgba(0,0,0,0.25);
    }

    .metric-card:hover {
        transform: scale(1.03);
        border-color: rgba(255,255,255,0.20);
        box-shadow: 0 14px 36px rgba(0,0,0,0.32);
    }

    /* -------------------------------------------
       BUTTONS
    ------------------------------------------- */
    .stButton>button {
        background: linear-gradient(135deg, #1E3A8A, #3B82F6);
        color: white;
        padding: 0.6rem 1.4rem;
        border-radius: 10px;
        border: none;
        font-weight: 600;
        transition: 0.25s ease;
        box-shadow: 0 10px 22px rgba(59, 130, 246, 0.28);
    }

    .stButton>button:hover {
        background: linear-gradient(135deg, #3B82F6, #60A5FA);
        transform: translateY(-2px);
    }

    /* -------------------------------------------
       SIDEBAR STYLING
    ------------------------------------------- */
    section[data-testid="stSidebar"] {
        background: #111827 !important;  /* Dark slate */
        border-right: 1px solid rgba(255,255,255,0.06);
    }

    /* -------------------------------------------
       SCROLLBAR
    ------------------------------------------- */
    ::-webkit-scrollbar {
        width: 6px;
    }
    ::-webkit-scrollbar-thumb {
        background: #374151;
        border-radius: 5px;
    }

    /* -------------------------------------------
       ANIMATIONS
    ------------------------------------------- */
    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(6px); }
        to { opacity: 1; transform: translateY(0); }
    }
    .fade-in {
        animation: fadeIn 0.6s ease forwards;
    }

    /* -------------------------------------------
       INPUTS + SELECTS
    ------------------------------------------- */
    .stNumberInput input, .stTextInput input, .stSelectbox [data-baseweb="select"] input {
        background: #111827 !important;
        border: 1px solid rgba(255,255,255,0.08) !important;
        color: #e5e7eb !important;
    }

    /* -------------------------------------------
       TABLES
    ------------------------------------------- */
    .dataframe tbody tr:hover {
        background: rgba(59,130,246,0.08) !important;
    }

    /* -------------------------------------------
       TAGS / BADGES
    ------------------------------------------- */
    .tag {
        display: inline-block;
        padding: 4px 10px;
        border-radius: 999px;
        font-size: 12px;
        border: 1px solid rgba(255,255,255,0.12);
        background: rgba(255,255,255,0.06);
    }

    /* -------------------------------------------
       HEADINGS TWEAKS
    ------------------------------------------- */
    h1, h2, h3, h4 {
        letter-spacing: 0.2px;
    }

    </style>
    """, unsafe_allow_html=True)