# -*- coding: utf-8 -*-
"""Home

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# =====================================================
# pages/1_🏠_Home.py
# Home Dashboard — Bankruptcy Early Warning Indicator
# =====================================================

import streamlit as st
from utils.visualization import inject_global_css

# Apply global dark/glass UI
inject_global_css()

# -----------------------------------------------------
# PAGE HEADER
# -----------------------------------------------------
st.markdown("<h1 class='fade-in'>🏠 Home Dashboard</h1>", unsafe_allow_html=True)
st.markdown("### Welcome to the Bankruptcy Early Warning Indicator Platform")


# -----------------------------------------------------
# METRIC CARDS (Animated placeholders until real data)
# -----------------------------------------------------
col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("<div class='metric-card fade-in'><h3>Total Analyses</h3><h2>0</h2></div>", unsafe_allow_html=True)

with col2:
    st.markdown("<div class='metric-card fade-in'><h3>Avg Portfolio Risk</h3><h2>—%</h2></div>", unsafe_allow_html=True)

with col3:
    st.markdown("<div class='metric-card fade-in'><h3>High-Risk Companies</h3><h2>—</h2></div>", unsafe_allow_html=True)


st.markdown("<br>", unsafe_allow_html=True)


# -----------------------------------------------------
# QUICK ACTION CARDS
# -----------------------------------------------------
st.markdown("## Quick Actions")

action_col1, action_col2, action_col3 = st.columns(3)

action_cards = [
    {
        "title": "Single Company Analysis",
        "desc": "Run a detailed bankruptcy risk assessment.",
        "icon": "🔍",
        "page": "pages/2_🔍_Analysis.py"
    },
    {
        "title": "Portfolio Upload",
        "desc": "Analyze multiple companies at once.",
        "icon": "📊",
        "page": "pages/4_📊_Portfolio.py"
    },
    {
        "title": "What-If Simulator",
        "desc": "Experiment with financial scenarios.",
        "icon": "🎮",
        "page": "pages/3_🎮_Simulator.py"
    }
]

cols = [action_col1, action_col2, action_col3]

for col, card in zip(cols, action_cards):
    with col:
        st.markdown(f"""
            <div class='glass-card fade-in'>
                <h2>{card['icon']} {card['title']}</h2>
                <p>{card['desc']}</p>
            </div>
        """, unsafe_allow_html=True)
        st.page_link(card["page"], label="Open")


st.markdown("<br><br>", unsafe_allow_html=True)


# -----------------------------------------------------
# RISK DISTRIBUTION GAUGE (PLACEHOLDER)
# -----------------------------------------------------
st.markdown("## Portfolio Health Gauge (Coming Soon)")

st.info("The animated risk gauge will appear here once batch data is connected.")