# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# =====================================================================
# pages/2_🔍_Analysis.py
# Single Company Analysis — Bankruptcy Early Warning Indicator
# PHASE 3:
# - Industry Benchmarks (CSV-driven)
# - Ratio Severity Scoring
# - Driver Spotlight Cards
# - Premium Layout Integration
# =====================================================================

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go

from utils.model_utils import load_model
from utils.feature_engineering import compute_features
from utils.shap_utils import compute_local_shap, get_top_shap_features, load_shap_explainer
from utils.visualization import inject_global_css
from utils.plot_helpers import plot_shap_waterfall, plot_radar_chart

# ------------------------------------------------------------
# PAGE SETUP
# ------------------------------------------------------------
inject_global_css()
st.markdown("<h1 class='fade-in'>Single-Company Analysis</h1>", unsafe_allow_html=True)
st.markdown("### Enter company financials to assess bankruptcy risk.")

# Show last result if present
last = st.session_state.get("last_analysis_result")
if last:
    st.markdown(
        f"""
        <div class='metric-card fade-in' style="margin-bottom:12px;">
            <h4>Last Result</h4>
            <p style="margin:0;">Probability: {last['proba']:.2%}</p>
            <p style="margin:0;">Risk: {last['label']}</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

# ------------------------------------------------------------
# LOAD MODEL + SHAP
# ------------------------------------------------------------
model = load_model()
shap_explainer = load_shap_explainer(model)

# ------------------------------------------------------------
# LOAD INDUSTRY BENCHMARKS (CSV REQUIRED)
# ------------------------------------------------------------
try:
    industry_df = pd.read_csv("data/industry_benchmarks.csv")
except:
    st.error("⚠️ industry_benchmarks.csv not found in /data folder.")
    industry_df = None


# ------------------------------------------------------------
# INPUT FORM SECTION
# ------------------------------------------------------------
st.markdown("## Financial Inputs")

c1, c2, c3 = st.columns(3)

with c1:
    current_assets = st.number_input("Current Assets", min_value=0.0, value=1_000_000.0)
    total_assets = st.number_input("Total Assets", min_value=0.0, value=2_000_000.0)
    inventory = st.number_input("Inventory", min_value=0.0, value=200_000.0)
    total_receivables = st.number_input("Total Receivables", min_value=0.0, value=150_000.0)
    total_current_liabilities = st.number_input("Current Liabilities", min_value=0.0, value=300_000.0)

with c2:
    total_liabilities = st.number_input("Total Liabilities", min_value=0.0, value=1_200_000.0)
    total_revenue = st.number_input("Total Revenue", min_value=0.0, value=3_000_000.0)
    net_sales = st.number_input("Net Sales", min_value=0.0, value=2_500_000.0)
    cost_of_goods_sold = st.number_input("COGS", min_value=0.0, value=1_000_000.0)
    gross_profit = st.number_input("Gross Profit", min_value=0.0, value=500_000.0)

with c3:
    ebitda = st.number_input("EBITDA", min_value=0.0, value=300_000.0)
    ebit = st.number_input("EBIT", min_value=0.0, value=250_000.0)
    net_income = st.number_input("Net Income", min_value=-5_000_000.0, value=100_000.0)
    retained_earnings = st.number_input("Retained Earnings", min_value=-5_000_000.0, value=500_000.0)
    market_value = st.number_input("Market Cap (Equity)", min_value=0.0, value=10_000_000.0)
    major_group = st.number_input("Industry Code (1–99)", min_value=1, max_value=99, value=37)


# ------------------------------------------------------------
# RUN ANALYSIS
# ------------------------------------------------------------
st.markdown("<br>", unsafe_allow_html=True)

if st.button("🚀 Run Bankruptcy Risk Assessment"):

    # -----------------------------
    # RAW DF
    # -----------------------------
    raw = pd.DataFrame([{
        "current_assets": current_assets,
        "cost_of_goods_sold": cost_of_goods_sold,
        "depreciation_amortization": 0.0,
        "ebitda": ebitda,
        "inventory": inventory,
        "net_income": net_income,
        "total_receivables": total_receivables,
        "market_value": market_value,
        "net_sales": net_sales,
        "total_assets": total_assets,
        "total_long_term_debt": total_liabilities - total_current_liabilities,
        "ebit": ebit,
        "gross_profit": gross_profit,
        "total_current_liabilities": total_current_liabilities,
        "retained_earnings": retained_earnings,
        "total_revenue": total_revenue,
        "total_liabilities": total_liabilities,
        "total_operating_expenses": total_revenue - gross_profit,
        "MajorGroup": major_group
    }])

    # -----------------------------
    # ENGINEERED FEATURES
    # -----------------------------
    feat = compute_features(raw)

    model_cols = list(getattr(model, "feature_names_", []))
    if not model_cols:
        st.error("Model feature names missing; ensure CatBoost model saved with feature_names_.")
        st.stop()
    feat = feat.reindex(columns=model_cols, fill_value=0.0)

    # -----------------------------
    # RULE-BASED GUARDRAILS
    # -----------------------------
    warnings = []
    override_proba = None

    # Basic sanity: total_assets and revenues must be positive
    if total_assets <= 0:
        warnings.append("Total assets are zero or negative; setting risk to critical.")
        override_proba = 0.99
    if net_sales <= 0 or total_revenue <= 0:
        warnings.append("Revenue/Net Sales are zero or negative; elevating risk.")
        override_proba = max(override_proba or 0, 0.85)

    # Leverage and liquidity checks
    leverage = total_liabilities / max(total_assets, 1e-6)
    if leverage >= 5:
        warnings.append(f"Leverage is extreme (>{leverage:.1f}x); elevating risk.")
        override_proba = max(override_proba or 0, 0.75)

    current_ratio = current_assets / max(total_current_liabilities, 1e-6)
    if current_ratio < 0.7:
        warnings.append("Current ratio below 0.7; liquidity is strained.")
        override_proba = max(override_proba or 0, 0.35)

    # -----------------------------
    # PREDICT RISK
    # -----------------------------
    if override_proba is not None:
        proba = override_proba
    else:
        proba = model.predict(feat)[0]

    risk_label = (
        "CRITICAL RISK" if proba >= 0.50 else
        "HIGH RISK" if proba >= 0.25 else
        "MODERATE RISK" if proba >= 0.10 else
        "LOW RISK"
    )

    # Persist result in session for sidebar + recall
    st.session_state["last_analysis_result"] = {"proba": proba, "label": risk_label}
    q = st.session_state.get("quick_stats", {})
    q.update({"single_proba": proba, "single_label": risk_label})
    st.session_state["quick_stats"] = q

    if warnings:
        st.warning(" | ".join(warnings))

    # ============================================================
    # SECTION 1 — RISK RESULT CARD
    # ============================================================
    st.markdown("## Bankruptcy Risk Result")

    st.markdown(f"""
        <div class='metric-card fade-in'>
            <h3>Bankruptcy Probability</h3>
            <h1>{proba:.2%}</h1>
            <p>{risk_label}</p>
        </div>
    """, unsafe_allow_html=True)


    # ============================================================
    # SECTION 2 — SHAP WATERFALL
    # ============================================================
    st.markdown("## 🔍 SHAP Waterfall Explanation")

    shap_values, base_value = compute_local_shap(shap_explainer, feat)
    waterfall_fig = plot_shap_waterfall(shap_values, base_value, feat.columns)
    st.plotly_chart(waterfall_fig, use_container_width=True)


    # ============================================================
    # SECTION 3 — KEY DRIVER SPOTLIGHT CARDS
    # ============================================================
    st.markdown("## 🚨 Key Risk Drivers")

    top_drivers = pd.DataFrame(get_top_shap_features(shap_values, feat.columns, top_n=5))

    cols = st.columns(5)

    for col, row in zip(cols, top_drivers.itertuples()):
        color = "#EF4444" if row.shap_value > 0 else "#10B981"
        direction = "Increases Risk" if row.shap_value > 0 else "Reduces Risk"

        col.markdown(f"""
        <div class='glass-card fade-in' style='border-left: 6px solid {color}; min-height:120px;'>
            <h4>{row.feature}</h4>
            <p style='margin:0;'>Impact: <b>{row.shap_value:.4f}</b></p>
            <p style='color:{color}; font-weight:bold;'>{direction}</p>
        </div>
        """, unsafe_allow_html=True)


    # ============================================================
    # SECTION 4 — INDUSTRY BENCHMARKS + SEVERITY SCORING
    # ============================================================
    st.markdown("## 🏭 Industry Comparison & Severity Assessment")

    if industry_df is None:
        st.warning("No industry benchmarks available.")
    else:
        # Pull medians for the selected industry
        bench = industry_df[industry_df["MajorGroup"] == major_group]

        if bench.empty:
            st.warning("No benchmark data for this industry.")
        else:
            bench = bench.iloc[0]

            company_vals = {
                "Leverage": feat["leverage"].iloc[0],
                "Profit Margin": feat["profit_margin"].iloc[0],
                "EBITDA Margin": feat["ebitda_margin"].iloc[0],
                "Revenue Efficiency": feat["revenue_efficiency"].iloc[0],
                "OPEX Ratio": feat["operating_expense_ratio"].iloc[0],
                "Working Capital Ratio": feat["working_capital_ratio"].iloc[0]
            }

            industry_vals = {
                "Leverage": bench["Leverage"],
                "Profit Margin": bench["ProfitMargin"],
                "EBITDA Margin": bench["EBITDAMargin"],
                "Revenue Efficiency": bench["RevenueEfficiency"],
                "OPEX Ratio": bench["OPEXRatio"],
                "Working Capital Ratio": bench["WorkingCapitalRatio"],
            }

            # --- UI driver cards
            cA, cB, cC = st.columns(3)

            for col, (metric, comp) in zip([cA, cB, cC], list(company_vals.items())[:3]):
                bench_val = industry_vals[metric]
                delta = comp - bench_val

                severity = "🟢 Healthy" if delta >= 0 else "🔴 Below Benchmark"

                col.markdown(f"""
                <div class='glass-card fade-in'>
                    <h4>{metric}</h4>
                    <p>Company: {comp:.3f}</p>
                    <p>Industry: {bench_val:.3f}</p>
                    <p><b>{severity}</b></p>
                </div>
                """, unsafe_allow_html=True)

            cD, cE, cF = st.columns(3)

            for col, (metric, comp) in zip([cD, cE, cF], list(company_vals.items())[3:]):
                bench_val = industry_vals[metric]
                delta = comp - bench_val

                severity = "🟢 Healthy" if delta >= 0 else "🔴 Below Benchmark"

                col.markdown(f"""
                <div class='glass-card fade-in'>
                    <h4>{metric}</h4>
                    <p>Company: {comp:.3f}</p>
                    <p>Industry: {bench_val:.3f}</p>
                    <p><b>{severity}</b></p>
                </div>
                """, unsafe_allow_html=True)


    # ============================================================
    # SECTION 5 — RADAR CHART WITH REAL BENCHMARK VALUES
    # ============================================================
    st.markdown("## 🛡 Financial Health Radar Chart")

    if industry_df is None:
        st.warning("Benchmark CSV needed for radar chart.")
    else:
        bench = industry_df[industry_df["MajorGroup"] == major_group]
        if not bench.empty:
            bench = bench.iloc[0]

            company_ratios = list(company_vals.values())
            industry_ratios = list(industry_vals.values())
            labels = list(company_vals.keys())

            radar_fig = plot_radar_chart(company_ratios, industry_ratios, labels)
            st.plotly_chart(radar_fig, use_container_width=True)