# -*- coding: utf-8 -*-
"""simulator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# =====================================================================
# pages/3_🎮_Simulator.py
# What-If Scenario Simulator — Phase 3 Upgrade
# - Delta SHAP Engine
# - AI Scenario Narrative
# - SHAP-Weighted Tornado Chart
# - Scenario Comparison Table
# =====================================================================

import streamlit as st
import pandas as pd
import numpy as np

from utils.model_utils import load_model
from utils.feature_engineering import compute_features
from utils.shap_utils import compute_local_shap, load_shap_explainer
from utils.visualization import inject_global_css
from utils.plot_helpers import plot_tornado_chart
from utils.ai_summary import generate_executive_summary

# ------------------------------------------------------------
# PAGE SETUP
# ------------------------------------------------------------
inject_global_css()

st.markdown("<h1 class='fade-in'>Scenario Simulator</h1>", unsafe_allow_html=True)
st.markdown("### Adjust financial variables and see how bankruptcy risk changes in real time.")


# ------------------------------------------------------------
# LOAD MODEL + SHAP
# ------------------------------------------------------------
model = load_model()
shap_explainer = load_shap_explainer(model)


# ------------------------------------------------------------
# BASELINE INPUTS
# ------------------------------------------------------------
st.markdown("## Baseline Financials")

b1, b2, b3 = st.columns(3)

with b1:
    base_revenue = st.number_input("Revenue", value=2_500_000.0)
    base_assets = st.number_input("Total Assets", value=2_000_000.0)
    base_wc = st.number_input("Working Capital", value=200_000.0)

with b2:
    base_cogs = st.number_input("COGS", value=1_000_000.0)
    base_liab = st.number_input("Total Liabilities", value=1_200_000.0)
    base_ebitda = st.number_input("EBITDA", value=300_000.0)

with b3:
    base_opex = st.number_input("Operating Expenses", value=900_000.0)
    base_net_income = st.number_input("Net Income", value=120_000.0)
    major_group = st.number_input("Industry Code (1–99)", 1, 99, 37)


# ------------------------------------------------------------
# ADJUSTMENT SLIDERS
# ------------------------------------------------------------
st.markdown("## 🎚️ Scenario Adjustments")

s1, s2 = st.columns(2)

with s1:
    adj_rev_pct = st.slider("Revenue Adjustment (%)", -50, 100, 0)
    adj_cogs_pct = st.slider("COGS Adjustment (%)", -50, 50, 0)
    adj_opex_pct = st.slider("OPEX Adjustment (%)", -50, 50, 0)

with s2:
    adj_liab_pct = st.slider("Liabilities Adjustment (%)", -50, 50, 0)
    adj_ebitda_pct = st.slider("EBITDA Adjustment (%)", -50, 100, 0)
    adj_wc_pct = st.slider("Working Capital Adjustment (%)", -50, 100, 0)


def apply(value, pct):
    return value * (1 + pct / 100)


# ------------------------------------------------------------
# BASELINE + SCENARIO DATAFRAMES
# ------------------------------------------------------------
def build_df(revenue, cogs, opex, assets, liab, ebitda, net_inc, wc, major_group):
    gross = revenue - cogs

    return pd.DataFrame([{
        "current_assets": wc + (liab * 0.3),
        "cost_of_goods_sold": cogs,
        "depreciation_amortization": 0.0,
        "ebitda": ebitda,
        "inventory": 0.2 * assets,
        "net_income": net_inc,
        "total_receivables": revenue * 0.15,
        "market_value": 10_000_000.0,
        "net_sales": revenue,
        "total_assets": assets,
        "total_long_term_debt": max(liab - wc, 0),
        "ebit": ebitda * 0.8,
        "gross_profit": gross,
        "total_current_liabilities": liab * 0.4,
        "retained_earnings": net_inc * 2.5,
        "total_revenue": revenue,
        "total_liabilities": liab,
        "total_operating_expenses": opex,
        "MajorGroup": major_group
    }])


baseline_df = build_df(
    base_revenue, base_cogs, base_opex, base_assets, base_liab,
    base_ebitda, base_net_income, base_wc, major_group
)

scenario_df = build_df(
    apply(base_revenue, adj_rev_pct),
    apply(base_cogs, adj_cogs_pct),
    apply(base_opex, adj_opex_pct),
    base_assets,
    apply(base_liab, adj_liab_pct),
    apply(base_ebitda, adj_ebitda_pct),
    base_net_income,
    apply(base_wc, adj_wc_pct),
    major_group
)


# ------------------------------------------------------------
# FEATURE ENGINEERING + ALIGNMENT
# ------------------------------------------------------------
# CatBoost models expose the training feature order via feature_names_.
# The saved pickle does not carry an MLflow signature, so avoid .metadata.
model_cols = list(getattr(model, "feature_names_", []))
if not model_cols:
    raise ValueError("Model feature names are missing; ensure CatBoost model saved with feature_names_.")

base_feat = compute_features(baseline_df).reindex(columns=model_cols, fill_value=0.0)
scen_feat = compute_features(scenario_df).reindex(columns=model_cols, fill_value=0.0)

# ------------------------------------------------------------
# RULE-BASED GUARDRAILS (same logic as analysis page)
# ------------------------------------------------------------
def guardrail_override(df_row):
    """
    Returns (override_proba, warning_list)
    """
    warnings = []
    override = None

    total_assets = df_row["total_assets"]
    net_sales = df_row["net_sales"]
    total_revenue = df_row["total_revenue"]
    total_liabilities = df_row["total_liabilities"]
    current_assets = df_row["current_assets"]
    total_current_liabilities = df_row["total_current_liabilities"]

    if total_assets <= 0:
        warnings.append("Total assets are zero or negative; setting risk to critical.")
        override = 0.99
    if net_sales <= 0 or total_revenue <= 0:
        warnings.append("Revenue/Net Sales are zero or negative; elevating risk.")
        override = max(override or 0, 0.85)

    leverage = total_liabilities / max(total_assets, 1e-6)
    if leverage >= 5:
        warnings.append(f"Leverage is extreme (>{leverage:.1f}x); elevating risk.")
        override = max(override or 0, 0.75)

    current_ratio = current_assets / max(total_current_liabilities, 1e-6)
    if current_ratio < 0.7:
        warnings.append("Current ratio below 0.7; liquidity is strained.")
        override = max(override or 0, 0.35)

    return override, warnings

b_override, b_warn = guardrail_override(baseline_df.iloc[0])
s_override, s_warn = guardrail_override(scenario_df.iloc[0])


# ------------------------------------------------------------
# PREDICT RISK SCORES
# ------------------------------------------------------------
base_pred = b_override if b_override is not None else model.predict(base_feat)[0]
scen_pred = s_override if s_override is not None else model.predict(scen_feat)[0]

def risk_label(p):
    return (
        "CRITICAL" if p >= 0.50 else
        "HIGH" if p >= 0.25 else
        "MODERATE" if p >= 0.10 else
        "LOW"
    )


# ------------------------------------------------------------
# DISPLAY RESULTS
# ------------------------------------------------------------
st.markdown("## 📊 Scenario Results")

r_warn = b_warn + s_warn
if r_warn:
    st.warning(" | ".join(r_warn))

r1, r2 = st.columns(2)

with r1:
    st.markdown(f"""
    <div class='metric-card fade-in'>
        <h3>Original Risk</h3>
        <h1>{base_pred:.2%}</h1>
        <p>{risk_label(base_pred)}</p>
    </div>
    """, unsafe_allow_html=True)

with r2:
    st.markdown(f"""
    <div class='metric-card fade-in'>
        <h3>New Risk</h3>
        <h1>{scen_pred:.2%}</h1>
        <p>{risk_label(scen_pred)}</p>
    </div>
    """, unsafe_allow_html=True)

delta = scen_pred - base_pred
arrow = "⬆️" if delta > 0 else "⬇️"
color = "red" if delta > 0 else "green"

st.markdown(f"### **Change: <span style='color:{color}'>{arrow} {delta:.2%}</span>**", unsafe_allow_html=True)


# ------------------------------------------------------------
# DELTA SHAP (sensitivity engine)
# ------------------------------------------------------------
st.markdown("## 🧠 SHAP Impact Change (Δ-SHAP)")

base_shap, _ = compute_local_shap(shap_explainer, base_feat)
scen_shap, _ = compute_local_shap(shap_explainer, scen_feat)

delta_shap = scen_shap - base_shap

delta_df = pd.DataFrame({
    "feature": model_cols,
    "delta_shap": delta_shap
}).sort_values("delta_shap", key=np.abs, ascending=False).head(10)

st.dataframe(delta_df)


# Tornado chart based on Δ-SHAP
tornado_fig = plot_tornado_chart(
    delta_df["feature"].tolist(),
    delta_df["delta_shap"].tolist()
)
st.plotly_chart(tornado_fig, use_container_width=True)


# ------------------------------------------------------------
# SCENARIO COMPARISON TABLE
# ------------------------------------------------------------
st.markdown("## 📘 Scenario Comparison Table")

compare_df = pd.DataFrame({
    "Metric": ["Revenue", "COGS", "OPEX", "Liabilities", "EBITDA", "Working Capital", "Risk Score"],
    "Baseline": [
        base_revenue, base_cogs, base_opex, base_liab, base_ebitda, base_wc, base_pred
    ],
    "Scenario": [
        scenario_df["net_sales"].iloc[0],
        scenario_df["cost_of_goods_sold"].iloc[0],
        scenario_df["total_operating_expenses"].iloc[0],
        scenario_df["total_liabilities"].iloc[0],
        scenario_df["ebitda"].iloc[0],
        scenario_df["current_assets"].iloc[0] - scenario_df["total_current_liabilities"].iloc[0],
        scen_pred
    ]
})

compare_df["Δ Change"] = compare_df["Scenario"] - compare_df["Baseline"]
st.dataframe(compare_df)


# ------------------------------------------------------------
# AI SCENARIO NARRATIVE
# ------------------------------------------------------------
st.markdown("## 📝 AI Scenario Narrative")

scenario_context = {
    "Baseline Risk": base_pred,
    "New Risk": scen_pred,
    "Revenue Change %": adj_rev_pct,
    "COGS Change %": adj_cogs_pct,
    "OPEX Change %": adj_opex_pct,
    "Liabilities Change %": adj_liab_pct,
    "EBITDA Change %": adj_ebitda_pct,
}

ai_narrative = generate_executive_summary(scenario_context, delta_df.to_dict("records"))
st.write(ai_narrative)