# -*- coding: utf-8 -*-
"""reports

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2onXIIBQqA8HsysUU_sAEAcYF06sosp
"""

# ======================================================================
# pages/5_📄_Reports.py
# Reports & Recommendations — Phase 3 Upgrade
# Adds:
# - Multi-company report generation
# - Scenario appendix section
# - Portfolio appendix integration
# ======================================================================

import streamlit as st
import pandas as pd
import tempfile
import io

from utils.model_utils import load_model
from utils.feature_engineering import compute_features
from utils.shap_utils import (
    compute_local_shap,
    get_top_shap_features,
    load_shap_explainer
)
from utils.ai_summary import generate_executive_summary, generate_ai_recommendations
from utils.plot_helpers import plot_shap_waterfall, plot_radar_chart
from utils.pdf_generator import generate_pdf
from utils.visualization import inject_global_css


# ------------------------------------------------------------
# PAGE SETUP
# ------------------------------------------------------------
inject_global_css()
st.markdown("<h1 class='fade-in'>Reports & Recommendations</h1>", unsafe_allow_html=True)
st.markdown("### Generate single-company or multi-company professional reports.")


# ------------------------------------------------------------
# LOAD MODEL + SHAP
# ------------------------------------------------------------
model = load_model()
shap_explainer = load_shap_explainer(model)


# ------------------------------------------------------------
# MODE SELECTION
# ------------------------------------------------------------
mode = st.radio(
    "Select Report Mode:",
    ["Single Company Report", "Multi-Company Portfolio Report"],
    horizontal=True
)

st.markdown("<br>", unsafe_allow_html=True)


# =====================================================================
# 1. SINGLE COMPANY REPORTING (unchanged except for improvements)
# =====================================================================
if mode == "Single Company Report":

    st.markdown("## Company Information")

    company_name = st.text_input("Company Name", "Example Corp")
    ticker = st.text_input("Ticker Symbol", "")

    st.markdown("## Financial Inputs")

    c1, c2, c3 = st.columns(3)

    with c1:
        revenue = st.number_input("Total Revenue", value=3_000_000.0)
        total_assets = st.number_input("Total Assets", value=2_000_000.0)
        current_assets = st.number_input("Current Assets", value=800_000.0)
        inventory = st.number_input("Inventory", value=200_000.0)
        net_sales = revenue  # align net_sales with revenue input for guardrails/feature set

    with c2:
        cogs = st.number_input("COGS", value=1_200_000.0)
        total_liabilities = st.number_input("Total Liabilities", value=1_300_000.0)
        current_liabilities = st.number_input("Current Liabilities", value=350_000.0)
        net_income = st.number_input("Net Income", value=150_000.0)

    with c3:
        ebitda = st.number_input("EBITDA", value=250_000.0)
        ebit = st.number_input("EBIT", value=200_000.0)
        retained_earnings = st.number_input("Retained Earnings", value=600_000.0)
        major_group = st.number_input("Industry Code (1–99)", 1, 99, 37)

    if st.button("🚀 Generate Single Company Report"):

        df = pd.DataFrame([{
            "current_assets": current_assets,
            "cost_of_goods_sold": cogs,
            "depreciation_amortization": 0.0,
            "ebitda": ebitda,
            "inventory": inventory,
            "net_income": net_income,
            "total_receivables": revenue * 0.15,
            "market_value": 10_000_000.0,
            "net_sales": revenue,
            "total_assets": total_assets,
            "total_long_term_debt": max(total_liabilities - current_liabilities, 0),
            "ebit": ebit,
            "gross_profit": revenue - cogs,
            "total_current_liabilities": current_liabilities,
            "retained_earnings": retained_earnings,
            "total_revenue": revenue,
            "total_liabilities": total_liabilities,
            "total_operating_expenses": revenue - (revenue - cogs),
            "MajorGroup": major_group
        }])

        # Engineering
        feat = compute_features(df)
        cols = list(getattr(model, "feature_names_", []))
        if not cols:
            st.error("Model feature names missing; ensure CatBoost model saved with feature_names_.")
            st.stop()
        feat = feat.reindex(columns=cols, fill_value=0.0)

        # Guardrails
        warnings = []
        override = None
        if total_assets <= 0:
            warnings.append("Total assets are zero or negative; setting risk to critical.")
            override = 0.99
        if revenue <= 0 or net_sales <= 0:
            warnings.append("Revenue/Net Sales are zero or negative; elevating risk.")
            override = max(override or 0, 0.85)
        leverage = total_liabilities / max(total_assets, 1e-6)
        if leverage >= 5:
            warnings.append(f"Leverage is extreme (>{leverage:.1f}x); elevating risk.")
            override = max(override or 0, 0.75)
        current_ratio = current_assets / max(current_liabilities, 1e-6)
        if current_ratio < 0.7:
            warnings.append("Current ratio below 0.7; liquidity is strained.")
            override = max(override or 0, 0.35)

        # Prediction
        proba = override if override is not None else model.predict(feat)[0]
        risk_label = (
            "Critical Risk" if proba >= 0.50 else
            "High Risk" if proba >= 0.25 else
            "Moderate Risk" if proba >= 0.10 else
            "Low Risk"
        )
        # Prediction
        proba = model.predict(feat)[0]
        risk_label = (
            "Critical Risk" if proba >= 0.50 else
            "High Risk" if proba >= 0.25 else
            "Moderate Risk" if proba >= 0.10 else
            "Low Risk"
        )

        # SHAP
        shap_vals, base = compute_local_shap(shap_explainer, feat)
        top_drivers = pd.DataFrame(get_top_shap_features(shap_vals, feat.columns, top_n=8))

        # Generate charts → temp PNGs
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp1:
            plot_shap_waterfall(shap_vals, base, feat.columns).write_image(tmp1.name)
            waterfall_path = tmp1.name

        # Radar chart placeholder values
        company_ratios = [
            feat["leverage"].iloc[0],
            feat["profit_margin"].iloc[0],
            feat["ebitda_margin"].iloc[0],
            feat["revenue_efficiency"].iloc[0],
            feat["operating_expense_ratio"].iloc[0],
            feat["working_capital_ratio"].iloc[0],
        ]

        radar = plot_radar_chart(
            company_ratios,
            [0.40, 0.08, 0.12, 0.80, 0.65, 0.10],
            ["Leverage","Profit Margin","EBITDA Margin","Revenue Efficiency","OPEX Ratio","Working Capital Ratio"]
        )

        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp2:
            radar.write_image(tmp2.name)
            radar_path = tmp2.name

        # AI Summary + Recommendations
        summary = generate_executive_summary(
            {"Company": company_name, "Revenue": revenue, "Assets": total_assets},
            top_drivers.to_dict("records")
        )
        recs = generate_ai_recommendations(
            {"Company": company_name, "Revenue": revenue},
            top_drivers.to_dict("records")
        )

        # PDF Build
        pdf_bytes = generate_pdf({
            "company_name": company_name,
            "risk_score": proba,
            "risk_label": risk_label,
            "shap_text_summary": summary,
            "recommendations": recs,
            "waterfall_image": waterfall_path,
            "radar_image": radar_path,
            "top_drivers_table": top_drivers
        })

        st.download_button(
            "📥 Download Report (PDF)",
            data=pdf_bytes,
            file_name=f"{company_name}_Report.pdf"
        )


# =====================================================================
# 2. MULTI-COMPANY REPORTING
# =====================================================================
if mode == "Multi-Company Portfolio Report":

    uploaded = st.file_uploader("Upload Portfolio CSV", type=["csv"])

    if uploaded:
        df = pd.read_csv(uploaded)
        st.success(f"Loaded {df.shape[0]} companies.")

        with st.expander("Preview Data"):
            st.dataframe(df.head())

        REQUIRED = [
            "current_assets","cost_of_goods_sold","depreciation_amortization","ebitda","inventory",
            "net_income","total_receivables","market_value","net_sales","total_assets",
            "total_long_term_debt","ebit","gross_profit","total_current_liabilities",
            "retained_earnings","total_revenue","total_liabilities","total_operating_expenses","MajorGroup"
        ]

        # Validation
        missing = [c for c in REQUIRED if c not in df.columns]
        if missing:
            st.error(f"Missing required columns: {missing}")
            st.stop()

        # Convert to numeric with cleaning (match portfolio handling)
        def _clean_numeric(series: pd.Series) -> pd.Series:
            ser = series.astype(str).str.strip()
            ser = ser.str.replace(r"[,$]", "", regex=True)
            ser = ser.str.replace(r"\(([^)]+)\)", r"-\1", regex=True)
            ser = ser.str.replace("%", "", regex=False)
            return pd.to_numeric(ser, errors="coerce")

        replacement_counts = {}
        for c in REQUIRED:
            cleaned = _clean_numeric(df[c])
            replacement_counts[c] = int(cleaned.isna().sum())
            df[c] = cleaned.fillna(0)

        total_replaced = sum(replacement_counts.values())
        if total_replaced > 0:
            st.warning(f"⚠️ Replaced {total_replaced} non-numeric/invalid entries with 0 across numeric columns.")
        else:
            st.success("✅ All numeric columns validated.")

        st.markdown("### Ready to Generate Full Portfolio Report")

        if st.button("📘 Generate Portfolio PDF"):

            # Engineer + predict
            feat = compute_features(df)
            cols = list(getattr(model, "feature_names_", []))
            if not cols:
                st.error("Model feature names missing; ensure CatBoost model saved with feature_names_.")
                st.stop()
            feat = feat.reindex(columns=cols, fill_value=0.0)

            df["bankruptcy_probability"] = model.predict(feat)

            # Build appendix
            appendix_rows = df.sort_values("bankruptcy_probability", ascending=False)

            # Build PDF
            pdf_bytes = generate_pdf({
                "portfolio_mode": True,
                "portfolio_table": appendix_rows,
                "company_name": "Portfolio Report",
                "risk_score": df["bankruptcy_probability"].mean(),
                "risk_label": "Portfolio Summary",
                "recommendations": [],
                "shap_text_summary": "",
                "waterfall_image": None,
                "radar_image": None,
                "top_drivers_table": None
            })

            st.download_button(
                "📥 Download Portfolio Report (PDF)",
                data=pdf_bytes,
                file_name="Portfolio_Report.pdf"
            )